name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.cloudinstitution }} -p ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Build and push Docker image
      run: |
        docker build -t docker pull cloudinstitution1/git:latest .
        docker push docker pull cloudinstitution1/git:latest
